apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}
  namespace: {{ .Values.nameSpace }}
  labels:
    app.kubernetes.io/name: {{ .Values.applicationName }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.applicationName }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.applicationName }}
    spec:
      containers:
        - name: {{ .Values.applicationName }}
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.applicationName }}
              containerPort: {{ .Values.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.cpuSize }}
              memory: {{ .Values.memorySize }}
