apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}
  namespace: {{ .Values.nameSpace }}
  labels:
    app.kubernetes.io/name: {{ .Values.applicationName }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.applicationName }}
  ports:
    - name: {{ .Values.applicationName }}
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
